version: "3.8"

services:
  lab-nginx:
    container_name: hidt-lab-nginx
    depends_on:
      - hidt-lab
      - hidt-lab-api
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  hidt-lab:
    container_name: hidt-lab
    image: sawlinthant/hidt-lab-web:latest
  hidt-lab-api:
    container_name: hidt-lab-api
    image: sawlinthant/hidt-lab-api:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports: 
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@kdm-lab-db/KDMLAB
      - SECRET_KEY=secret
      - ALGORITHM=HS256
    depends_on:
      - kdm-lab-db
  kdm-lab-db:
    container_name: kdm-lab-db
    image: postgres:13-alpine
    volumes:
      - kdm-lab-data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=KDMLAB
volumes:
  kdm-lab-data:
